#pragma once

#define CSSET_GLFW_SAMPLES_VALUE 4
#define CSSET_WINDOW_WIDTH 1280
#define CSSET_WINDOW_HEIGHT 720
#define CSSET_WINDOW_NAME "ClothSimCUDA"
#define CSSET_WINDOW_FOV 70.0f
#define CSSET_WINDOW_NEAR 0.1f
#define CSSET_WINDOW_FAR 1000.0f
static const float CSSET_WINDOW_RATIO = ((float)CSSET_WINDOW_WIDTH / (float)CSSET_WINDOW_HEIGHT);
static const float CSSET_CLEAR_COLORS[4] { 0.2f, 0.2f, 0.2f, 1.0f };