#pragma once

#include "Common.h"

// GRAPHICS

#define CSSET_GLFW_SAMPLES_VALUE 4
#define CSSET_WINDOW_WIDTH 1280
#define CSSET_WINDOW_HEIGHT 720
#define CSSET_WINDOW_NAME "ClothSimCUDA"
#define CSSET_WINDOW_FOV 70.0f
#define CSSET_WINDOW_NEAR 0.1f
#define CSSET_WINDOW_FAR 1000.0f
#define CSSET_VSYNC_ENALBED 0
static const float CSSET_WINDOW_RATIO = ((float)CSSET_WINDOW_WIDTH / (float)CSSET_WINDOW_HEIGHT);
static const float CSSET_CLEAR_COLORS[4] { 0.2f, 0.2f, 0.2f, 1.0f };

///////////////////

// INPUT

#ifdef BUILD_OPENGL
	#define CSSET_CAMERA_ROTATE_SPEED 4.0f
	#define CSSET_CAMERA_MOVE_SPEED 6.0f
	#define CSSET_CAMERA_ZOOM_SPEED 1.5f
#elif BUILD_OPENGLES
	#define CSSET_CAMERA_ROTATE_SPEED 0.01f
	#define CSSET_CAMERA_MOVE_SPEED 0.01f
	#define CSSET_CAMERA_ZOOM_SPEED 0.1f
#endif

#define CSSET_CAMERA_ROTATE_BARRIER 0.1f
#define CSSET_CAMERA_ZOOM_BARRIER_MIN 1.0f
#define CSSET_CAMERA_ZOOM_BARRIER_MAX 100.0f
#define CSSET_CAMERA_POSITION_MAX 100.0f

////////////////////