#pragma once

#include "Common.h"

// GRAPHICS

#define CSSET_GLFW_SAMPLES_VALUE 4
#define CSSET_WINDOW_WIDTH_DEFAULT 800
#define CSSET_WINDOW_HEIGHT_DEFAULT 600
#define CSSET_WINDOW_NAME "ClothSim"
#define CSSET_WINDOW_FOV 0.6f
#define CSSET_WINDOW_NEAR 0.1f
#define CSSET_WINDOW_FAR 200.0f
#define CSSET_VSYNC_ENALBED 0
#define CSSET_BACKFACE_CULLING 0
static const float CSSET_WINDOW_RATIO_DEFAULT = ((float)CSSET_WINDOW_WIDTH_DEFAULT / (float)CSSET_WINDOW_HEIGHT_DEFAULT);
static const float CSSET_CLEAR_COLORS[4] { 0.2f, 0.2f, 0.2f, 1.0f };

///////////////////

// INPUT

#define CSSET_CAMERA_ROTATE_SPEED 0.005f
#define CSSET_CAMERA_MOVE_SPEED 0.02f
#define CSSET_CAMERA_ZOOM_SPEED 0.1f

#define CSSET_CAMERA_ROTATE_BARRIER 0.9f
#define CSSET_CAMERA_ROTATE_MIN_Y 0.01f
#define CSSET_CAMERA_ZOOM_BARRIER_MIN 1.0f
#define CSSET_CAMERA_ZOOM_BARRIER_MAX 100.0f
#define CSSET_CAMERA_POSITION_MAX 100.0f

////////////////////